# Доступные зачеия Explorers:
# ClientLic - Клиентские лицензии
# AvailablePerformance - Доступная производительность (через RAC)
# SheduleJob - Проверка галки "блокировка регламентных заданий"
# Session - Сеансы
# Connect - Соединения
# SessionsData - различные показарели из консоли 1с  (через RAC)
# ProcData - Данные поцессов (получается из ОС, пока поддерживается только linux)
# CPU - загрузка ЦПУ
# disk - метрики дикска, пока только linux и WeightedIO
# Property - доп. свойства, у каждой метрики свои могут быть.
# у ProcData доп. свойство processes определяет список процессов которые нужно мониторить
# у всех метрик доп. свойство timerNotyfy время опроса в секундах (через какой интервал будут запрашиваться метрики). Если не задан по дефолту 10 сек.
Explorers:
- Name: ClientLic
  Property:
    timerNotyfy: 60
- Name: AvailablePerformance
  Property: 
    timerNotyfy: 10
- Name: CPU
  Property:
    timerNotyfy: 10
- Name: disk
  Property:
    timerNotyfy: 10
- Name: SheduleJob
  Property:
    timerNotyfy: 10
- Name: Session
  Property:
    timerNotyfy: 60
- Name: Connect
  Property:
    timerNotyfy: 60
- Name: SessionsData
  Property:
    timerNotyfy: 10
- Name: ProcData
  Property:
    processes:
      - rphost
      - ragent
      - rmngr
    timerNotyfy: 10
MSURL: http://ca-fr-web-1/fresh/int/sm/hs/PTG_SysExchange/GetDatabase # Не обязательный параметр
MSUSER: RemoteAccess                                                  # Не обязательный параметр
MSPAS: dvt45hn                                                        # Не обязательный параметр
RAC: "/opt/1C/v8.3/x86_64/rac"
LogDir: /var/log/1c_exporter  # Если на задан логи будут писаться в каталог с исполняемым файлом
LogLevel: 5                   # Уровень логирования от 2 до 6, где 2 - ошибка, 3 - предупреждение, 4 - информация, 5 - дебаг, 6 - трейс
TimeRotate: 1                 # Время в часах через которое будет создаваться новый файл логов
TTLLogs: 8                    # Время жизни логов в часах
